# Milvus extract tool configuration
# Use with: python extract.py -f extract_config.yaml  (or: click run extract.py -f extract_config.yaml)

extract:
  # Database name (string, mandatory). Default: 'default'
  database: milvus_image_db

  # Collection name (string, mandatory). Default: ''
  collection: 'prod_ann5'

  # Milvus endpoint (string, mandatory). Default: https://localhost:19530
  endpoint: http://localhost:19530

  # API key / token for Milvus (string, mandatory). Will be read from .env file.

  # Batch size for query_iterator (int, 1–16384). Default: 2000
  buffer: 200

  # Maximum rows per file (int) created by the writer. Default: 10000
  max_rows_per_file: 2000

  # Scalar filter expression (string). Empty = no filtering. Default: ''
  filter_expression: ''

  # Export format: 'JSON' or 'PARQUET' (string). Default: PARQUET
  export_file_type: PARQUET

  # Output destination: file:///path/to/file
  # Output destination or s3://bucket/remote/path -- NOTE: bucket is not needed if cloud_storage_params.storage_root is set
  output_location: file://Users/rohitn/tmp/milvus_export
  #output_location: s3://a-bucket/milvus_export

  # Cloud storage (S3-compatible) parameters
  cloud_storage_params:
    # Endpoint (string). Default: 'localhost:9000' for minio
    # use s3.amazonaws.com for AWS
    # use storage.googleapis.com for Google Cloud
    endpoint: 'localhost:9000'  
    # Access key (string, mandatory)
    access_key: 'minioadmin'
    # Secret key (string, mandatory)
    secret_key: 'minioadmin'
    # Storage root / bucket (string, mandatory). Default: 'a-bucket'
    storage_root: 'a-bucket'
